[build]
    command = "npm run build"
    publish = "landing-page/.next"

[build.environment]
  NODE_VERSION = "20.11.0"

[[plugins]]
  package = "@netlify/plugin-local-install-core"

[[plugins]]
package = "@netlify/plugin-emails"

[functions]
  directory = "core/src/api"

[[edge_functions]]
  path = "/core/src/api/geo" 
  function = "injectGeoCookie"
  
